apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
  namespace: today-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      initContainers:
      - name: init-patient-app
        image: busybox
        command: ['sh', '-c', 'echo init container initializing && sleep 5']
      containers:
      - name: patient-app
        image: 273354635930.dkr.ecr.us-east-1.amazonaws.com/patient-service:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
