name: app-build-push

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_PS: patient-service
  ECR_REPOSITORY_AS: appointment-service
  IMAGE_TAG: latest
  AWS_ACCOUNT_ID: 273354635930

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::273354635930:role/github-oidc
          aws-region: us-east-1
  
      - name: Create ECR
        run: |
          aws ecr create-repository --repository-name $ECR_REPOSITORY_PS || echo "Repository already exists"
          aws ecr create-repository --repository-name $ECR_REPOSITORY_AS || echo "Repository already exists"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build patient-service Docker image
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_PS:$IMAGE_TAG -f app/patient-service/Dockerfile app/patient-service

      - name: Build appointment-service Docker image
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_AS:$IMAGE_TAG -f app/appointment-service/Dockerfile app/appointment-service

      - name: Push patient-service Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_PS:$IMAGE_TAG
          
      - name: Push appointment-service Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_AS:$IMAGE_TAG
